version: '3.7'

networks:
  ngt-webapi-network:
    name: ngt-webapi-network
    driver: bridge

services:
  ngtmpi:
    image: ngt_ship_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - ngtdb
    ports:
      - "8081:80"
    networks:
      - ngt-webapi-network

  ngtdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ngtdb
    hostname: ngtdb
    environment:
      - ACCEPT_EULA=1
      - SA_PASSWORD=!qaz2wsxA
      - MSSQL_TCP_PORT=1433
    ports:
      - "1433:1433"
    networks:
      - ngt-webapi-network
       
  